version: '3'

services:
  frontend:
    build:
      context: ../../../../
      dockerfile: ./frontend/src/main/docker/Dockerfile
    image: jankagramofonomanka/analytics-platform-aggregate-processor
    container_name: aggregate-processor
    environment:
      AEROSPIKE_HOSTNAME: ${AEROSPIKE_HOSTNAME}
      AEROSPIKE_PORT: 3000
      KAFKA_TOPIC: tags-to-aggregate
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP: ${KAFKA_GROUP}
