version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: local-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: local-broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    
    command: sh -c "((sleep 15 && kafka-topics --bootstrap-server localhost:9092 --topic tags-to-aggregate --create --partitions 10)&) && /etc/confluent/docker/run "
    
    
  
  
  aerospike:
    image: aerospike/aerospike-server:5.7.0.16 
    volumes:
      - ./database/src/main/resources/:/etc/aerospike/
    command: ["--config-file", "/etc/aerospike/aerospike-local.conf"]
    container_name: local-aerospike
    ports:
      - 3000-3002:3000-3002
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/src/main/docker/Dockerfile
    container_name: local-frontend
    image: ${DOCKER_USERNAME}/analytics-platform-frontend
    depends_on:
      - kafka
      - aerospike
    ports:
      - 8080:8080
    network_mode: host
    
  aggregate-processor:
    build:
      context: .
      dockerfile: ./aggregate-processor/src/main/docker/Dockerfile
    container_name: local-aggregate-processor
    image: ${DOCKER_USERNAME}/analytics-platform-aggregate-processor
    depends_on:
      - kafka
      - aerospike
    network_mode: host
    
