version: '3'

services:
  frontend:
    image: ${DOCKER_USERNAME}/analytics-platform-frontend
    container_name: frontend
    ports:
      - 8080:8080
    network_mode: host
    environment:

      NUM_TAGS_TO_KEEP: 200
      DEFAULT_LIMIT: 200

      AEROSPIKE_HOSTNAME: ${AEROSPIKE_HOSTNAME}
      AEROSPIKE_PORT: ${AEROSPIKE_PORT}
      AEROSPIKE_NAMESPACE: analyticsplatform
      AEROSPIKE_PROFILES_SET: profiles
      AEROSPIKE_AGGREGATES_SET: aggregates
      AEROSPIKE_PROFILES_BIN: profile
      AEROSPIKE_AGGREGATES_BIN: aggregate

      KAFKA_TOPIC: tags-to-aggregate
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      
      FRONTEND_HOSTNAME: "0.0.0.0"
      FRONTEND_PORT: 8080
